# Generated by Django 5.2.4 on 2025-07-15 02:59

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Developer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Developer Name')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email Address')),
                ('github_username', models.CharField(blank=True, max_length=100, verbose_name='GitHub Username')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created At')),
            ],
            options={
                'verbose_name': 'Developer',
                'verbose_name_plural': 'Developers',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Project Name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('repository_url', models.URLField(blank=True, verbose_name='Repository URL')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created At')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ProductivityMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Date')),
                ('commit_count', models.IntegerField(default=0, verbose_name='Commit Count')),
                ('lines_added', models.IntegerField(default=0, verbose_name='Lines Added')),
                ('lines_deleted', models.IntegerField(default=0, verbose_name='Lines Deleted')),
                ('productivity_score', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Productivity Score')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created At')),
                ('developer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='dev_productivity.developer')),
            ],
            options={
                'verbose_name': 'Productivity Metric',
                'verbose_name_plural': 'Productivity Metrics',
                'ordering': ['-date'],
                'unique_together': {('developer', 'date')},
            },
        ),
    ]
